WIP: trust-graph service
fluencelabs/trust-graph pull request #18
Opened 2021-09-30 16:05 UTC by justprosh

TBD

2021-11-10 15:27 UTC, folex commented on .circleci/config.yml
> +          rustup target add wasm32-wasi --toolchain nightly-2021-04-24-x86_64-unknown-linux-gnu
Let's move toolchain requirements to `rust-toolchain.toml`? This way, everyone will have the same toolchain.

2021-11-10 15:55 UTC, folex requested changes

2021-11-10 15:55 UTC, folex commented on .github/workflows/release.yml
> +          java-version: '11'
I think Java isn't needed here

2021-11-10 15:55 UTC, folex commented on Cargo.toml
> +version = "0.2.9"
0.3.0 maybe? You've rewritten the whole thing and changed a lot of APIs. Isn't it a breaking change?

2021-11-10 15:55 UTC, folex commented on admin/README.md
> +4. Put `root_secret_key.ed25519` and `issuer_secret_key.ed25519` to folder
Where do I get these keys?

2021-11-10 15:55 UTC, folex commented on admin/index.ts
> +    let node = local[0].peerId;
You seem to ignore `environment` here.

2021-11-10 15:55 UTC, folex commented on admin/index.ts
> +console.log("📘 Will connect to local nodes");
Let's add an option to connect to krasnodar, testnet and stage. Here's an example https://github.com/fluencelabs/examples/blob/ff4f4075b92244382416910114dffc6f564d1be4/aqua-examples/aqua-ipfs-integration/nodejs/src/demo.ts#L120-L136

2021-11-10 15:55 UTC, folex commented on admin/package.json
> +    "@fluencelabs/fluence-network-environment": "^1.0.10",
Let's use latest Aqua and FluenceJS

2021-11-10 15:55 UTC, folex commented on aqua/package.json
> +    "@fluencelabs/aqua": "^0.3.1-228"
ditto

2021-11-10 15:55 UTC, folex commented on aqua/trust-graph-api.aqua
> +import "trust-graph.aqua"
Any documentation on all these functions? Link to documentation?

2021-11-10 15:55 UTC, folex commented on aqua/trust-graph-api.aqua
> +    <- result!
We decided to move that function inside Rust service, right? If you want to do that in the separate PR, then create an issue and add `TODO:` with link to that issue.

2021-11-10 15:55 UTC, folex commented on builtin-package/on_start.air
> +           (call %init_peer_id% ("op" "return") [add_root_res.$.error!])
Since async AquaVM, you need to return to `relay`. Here and everywhere else.

2021-11-10 15:55 UTC, folex commented on admin/index.ts
> +    fs.writeFileSync("../builtin-package/on_start.json", JSON.stringify({certs: certificates}));
You need to mention that `on_start.json` generation is important. In README, maybe somewhere else as well.

2021-11-10 15:55 UTC, folex commented on .github/workflows/release.yml
> +          prerelease: false
```suggestion
          prerelease: false
          fail_on_unmatched_files: true
```

2021-11-10 15:55 UTC, folex commented on example/index.ts
> +    let add_root_result = await add_root(local[0].peerId, local[0].peerId, 2);
You're ignoring `environment`

2021-11-10 15:55 UTC, folex commented on example/index.ts
> +async function main(environment: Node[]) {
This example does poor job of communicating what happens. Plz reconsider what messages you show to a user and how will she learn from these messages.

2021-11-10 15:55 UTC, folex commented on example/package.json
> +    "@fluencelabs/fluence": "0.14.2",
Different Aqua version from everything else. Update it everywhere to latest, plz.

2021-11-10 15:55 UTC, folex commented on keypair/src/error.rs
> +    #[error("Failed to verify signature  with ed25519: {0}")]
```suggestion
    #[error("Failed to verify signature with ed25519: {0}")]
```

2021-11-10 15:55 UTC, folex commented on keypair/src/error.rs
> +pub enum VerificationError {
I wish the error would show both signature and the public key, but that maybe too much

2021-11-10 15:55 UTC, folex commented on keypair/src/key_pair.rs
> +            Rsa(kp) => Keypair::Rsa(unsafe {
`// SAFETY` comment

2021-11-10 15:55 UTC, folex commented on service/Config.toml
> +modules_dir = "artifacts/"
indentation

2021-11-10 15:55 UTC, folex commented on service/build.rs
> +fn main() {
nice!

2021-11-10 15:55 UTC, folex commented on service/rust-toolchain
> +nightly
set specific nightly version

2021-11-10 15:55 UTC, folex commented on service/src/dto.rs
> +        .map_err(|e| DtoConversionError::PeerIdDecodeError(e.to_string()))?;
From the errors, you couldn't tell if error happened when decoding `revoked_peer_id` or `revoked_by`, could you?

To alleviate this, you need to show field name in the error.

2021-11-10 15:55 UTC, folex commented on service/src/dto.rs
> +        let signature = Signature::from_bytes(KeyFormat::from_str(&r.sig_type)?, signature);
Here you don't provide any information about which fields caused the error. You sure it's ok?

2021-11-10 15:55 UTC, folex commented on service/src/main.rs
> +#![allow(dead_code)]
why?

2021-11-10 15:55 UTC, folex commented on service/src/service_api.rs
> +    MAX_WEIGHT_FACTOR - max_chain_len
Underflow check?

2021-11-10 15:55 UTC, folex commented on service/src/service_api.rs
> +    let init_peer_id = call_parameters.init_peer_id.clone();
Why clone?

2021-11-10 15:55 UTC, folex commented on service/src/service_api.rs
> +use crate::dto::{Certificate, Revoke, Trust};
Docs on public methods?

2021-11-11 11:01 UTC, justprosh commented on admin/README.md
> +4. Put `root_secret_key.ed25519` and `issuer_secret_key.ed25519` to folder
i will store in some place in notion, I think. You can suggest a better alternative

2021-11-12 13:07 UTC, folex approved these changes

2021-11-12 13:19 UTC, merged