Error handling [WIP]
fluencelabs/trust-graph pull request #2
Opened 2021-02-10 12:31 UTC by DieMyst

2021-02-10 13:11 UTC, folex reviewed
- mv bin wasm
- Ok({}) => Ok(())

2021-02-10 13:11 UTC, folex commented on bin/src/storage_impl.rs
> +pub enum SqliteStorageError {
I think it's better to avoid storing messages inside enum variants. Why not inscribe them in the macro?
```
#[error("cannot convert weight to integer")]
WeightConversionError
```

instead of 
```
enum {
#[error("{}")]
ConversionError(String)
}

ConversionError("cannot get weight as integer".to_string())
```

2021-02-10 13:11 UTC, folex commented on src/certificate.rs
> +impl From<CertificateError> for String {
better implement Display

2021-02-10 13:11 UTC, folex commented on src/trust.rs
> +    #[error("{0:?}")]
```suggestion
    #[error("{0}")]
```

2021-02-10 13:11 UTC, folex commented on src/trust.rs
> +    #[error("{0:?}")]
```suggestion
    #[error("{0}")]
```

2021-02-10 13:11 UTC, folex commented on src/trust_graph_storage.rs
>  pub trait Storage {
I suggest shorting types so the definition is tidier:
```
use crate::public_key_hashable::PublicKeyHashable as PK;
...
pub trait Storage {
   type Error;
   type Result<T> = std::result::Result<T, Self::Error>
   ...
}
```

2021-02-10 13:11 UTC, folex commented on src/trust_graph_storage.rs
> +impl From<InMemoryStorageError> for String {
better implement Display

2021-02-10 13:11 UTC, folex commented on src/trust_graph_storage.rs
> +        Ok({})
```suggestion
        Ok(())
```

2021-02-10 13:11 UTC, folex commented on src/trust_graph_storage.rs
> +                Ok({})
```suggestion
                Ok(())
```

2021-02-12 12:53 UTC, folex requested changes

2021-02-12 12:53 UTC, folex commented on src/certificate.rs
> +    MalformedRoot(TrustError),
```suggestion
    MalformedRoot(#[source] TrustError),
```

2021-02-12 12:53 UTC, folex commented on src/certificate.rs
> +    DecodeTrustError(usize, TrustError),
do that everywhere plz
```suggestion
    DecodeTrustError(usize, #[source]TrustError),
```

2021-02-12 12:53 UTC, folex commented on src/certificate.rs
> +    DecodeError(TrustError),
Can you just do?
```suggestion
    DecodeError(#[from]TrustError),
```

and maybe also #[source], not sure. That way, you can drop `map_err(DecodeError)` and just use `?`

2021-02-12 12:53 UTC, folex commented on src/trust.rs
> +    DecodePublicKeyError(String, PKError),
add #[source] here and below plz

2021-02-12 12:53 UTC, folex commented on src/trust.rs
> +    #[error("{0}")]
#[error(transparent)]

2021-02-12 12:53 UTC, folex commented on wasm/src/service_impl.rs
> +}
```suggestion
pub enum ServiceError {
    #[error(transparent)]
    PublicKeyDecodeError(#[from] PKError),
    #[error(transparent)]
    TGError(#[from] TrustGraphError),
    #[error(transparent)]
    CertError(#[from] CertificateError),
    #[error(transparent)]
    DtoError(#[from] DtoConversionError),
}
```

2021-02-12 12:53 UTC, folex commented on wasm/src/storage_impl.rs
>      #[error("{0}")]
transparent

2021-02-12 12:53 UTC, folex commented on wasm/src/storage_impl.rs
> +    #[error("{0}")]
transparent

2021-02-15 09:15 UTC, DieMyst commented on src/certificate.rs
> +    MalformedRoot(TrustError),
i cannot have two #[from] from the same classes. `Into` can't choose which error to create

2021-02-15 10:04 UTC, merged