High-level Aqua API
fluencelabs/trust-graph pull request #35
Opened 2022-01-11 14:02 UTC by justprosh

2022-01-11 14:48 UTC, folex requested changes

2022-01-11 14:48 UTC, folex commented on aqua/trust-graph-api.aqua
>  import "trust-graph.aqua"
Documentation?

2022-01-11 14:48 UTC, folex commented on aqua/trust-graph-api.aqua
> +func issue_revocation(revoked_peer_id: string) -> ?Revocation, ?string:
Is this function a part of public API too?

2022-01-11 14:48 UTC, folex commented on aqua/trust-graph-api.aqua
>    array_length(a: []bool) -> u32
move to a separate file? Why is it part of the public API?

2022-01-11 14:48 UTC, folex commented on aqua/trust-graph-api.aqua
> +func isFluencePeer() -> ?bool, ?string:
move to `example/aqua`?

2022-01-11 14:48 UTC, folex commented on example/aqua/computation.aqua
> +
everything  in this file should be commented@explained

2022-01-11 14:48 UTC, folex commented on example/index.ts
This is an example, an educational material. Everything should be documented@explained.

2022-01-13 23:10 UTC, justprosh commented on aqua/trust-graph-api.aqua
> +func issue_revocation(revoked_peer_id: string) -> ?Revocation, ?string:
Yeah, user should have possibility to generate revocation and store it/propagate to other nodes

2022-01-13 23:11 UTC, justprosh commented on aqua/trust-graph-api.aqua
> +func isFluencePeer() -> ?bool, ?string:
Why? It's not an example, it's useful function

2022-01-19 09:35 UTC, folex approved these changes

2022-01-26 17:14 UTC, folex reviewed
I feel that all mentions of "on current node" should be dropped from doc-comments. Instead, there should be some short explanation in the documentation.

2022-01-26 17:14 UTC, folex commented on aqua/trust-graph-api.aqua
> +    on HOST_PEER_ID:
why use HOST_PEER_ID here while everywhere else you don't?

2022-01-26 17:14 UTC, folex commented on aqua/trust-graph-api.aqua
>      if bytes.success:
need a comment mentioning what could go wrong so `get_trust_bytes` fails

2022-01-26 17:14 UTC, folex commented on aqua/trust-graph-api.aqua
> +            Sig "sig"
need a comment explaining what's happening here

2022-01-26 17:43 UTC, folex reviewed
- I don't understand the change from `add_root` to `set_root`. Why?
- Are there tests on Aqua API?

2022-01-26 17:43 UTC, folex commented on aqua/trust-graph-api.aqua
>  -- Get maximum weight of trust among all chains which contain trust from `issuer`
Doc doesn't mention `peer_id`. Please explain usage of `peer_id` argument in the doc-comment.

2022-01-26 17:43 UTC, folex commented on aqua/trust-graph-api.aqua
> +        signature <- Sig.sign(bytes.result)
Seems like you use that pattern at least several times. Maybe move to a function?

2022-01-26 17:43 UTC, folex commented on aqua/trust-graph-api.aqua
>      certs_result <- get_host_certs_from("12D3KooWM45u7AQxsb4MuQJNYT3NWHHMLU7JTbBV66RTfF3KSzdR")
Please explain the hardcoded peer id. Over all, I think this function should be in a separate file called `labeling.aqua` or `labeling-api.aqua`

2022-01-26 17:43 UTC, folex commented on builtin-package/on_start.air
>  (seq
Comments?

2022-01-26 17:43 UTC, folex commented on service/src/results.rs
> +pub struct ExportRevocationsResult {
What does `Export` mean here?

2022-01-26 17:43 UTC, folex commented on src/revoke.rs
>      #[allow(dead_code)]
why do you need dead_code here?

Also, why do you have two `struct Revocation`? Sometimes it's `trust_graph::Revocation`, sometimes `dto::Revocation`, but never `revoke::Revocation`.

2022-01-26 17:43 UTC, folex commented on service/src/service_api.rs
> +        Ok(trust_graph::Revocation::new(revoked_by_pk, revoked_pk, revoked_at, signature).into())
Wow :) So you've swapped two arguments of the same type. Why? Let's add a comment so it's clear what is happening here?

Also, to avoid such errors you can use structure initialization directly. Especially given that `new` doesn't anything except structure initialization.

2022-01-26 17:43 UTC, folex commented on src/trust_graph.rs
> +        Ok(self.storage.get_revocations(issued_for.borrow().as_ref())?)
You sure you need `borrow().as_ref()`? Borrow and AsRef are very alike, it's unusual to combine them.

2022-01-26 20:05 UTC, justprosh commented on service/src/service_api.rs
> +        Ok(trust_graph::Revocation::new(revoked_by_pk, revoked_pk, revoked_at, signature).into())
It's for consistency. In all trust's methods issuer comes first so i do the same with revocations

2022-01-26 20:07 UTC, justprosh commented on src/revoke.rs
>      #[allow(dead_code)]
`revoke::Revocation` is same as `trust_graph::Revocation` because `trust_graph` is other crate for service itself.
dead_code is very old, i will check and remove

2022-01-27 11:02 UTC, justprosh commented on aqua/trust-graph-api.aqua
> +        signature <- Sig.sign(bytes.result)
afaik there is no way now to resolve service in other function scope

2022-01-27 11:04 UTC, justprosh commented on README.md
> +   assert(relay !== null);
because without assert compilation will fail with
```
 error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.
```

2022-01-27 11:06 UTC, justprosh commented on README.md
> +   assert(error == null)
nope, maybe better to rewrite with if/else
yeah, `===` will be better

2022-01-27 11:08 UTC, justprosh commented on aqua/trust-graph-api.aqua
>  -- Set peer_id as a root to TG instance on current node
I changed to `set_root` because you can change max_chain_len to existent root and yeah, there can be several roots

2022-01-30 18:40 UTC, justprosh commented on src/trust_graph.rs
> +        Ok(self.storage.get_revocations(issued_for.borrow().as_ref())?)
borrow() borrows reference to &PublicKey and as_ref() convert to &PublicKeyHashable

2022-01-30 18:41 UTC, justprosh commented on service/src/results.rs
> +pub struct ExportRevocationsResult {
export_revocations() returns all revocations for a given peer id that can be propagated to another peers

2022-02-04 15:45 UTC, merged