Identity rework
fluencelabs/trust-graph pull request #6
Opened 2021-04-07 12:43 UTC by justprosh

2021-04-07 13:51 UTC, folex requested changes

2021-04-07 13:51 UTC, folex commented on identity/src/ed25519.rs
> +        let secret = SecretKey::from_bytes(&mut sk_bytes)
It seems that `from_bytes` will zeroize `sk_bytes`. I'm not sure that's an expected behaviour. 
```
let keypair_a = ...;
let keybpair_b = keypair_a.clone(); // <-- keypair_a is now invalid since its secret key is zeroized
```

2021-04-07 14:49 UTC, folex requested changes
I'm not sure on the current pattern with zeroizing. I see two options:
1. Either change all `decode`-like function to accept `bytes: &mut [u8]` and zeroize it
2. Or accept `bytes: Vec<u8>`, then zeroize it and drop.

First one puts risk on the caller - if they're not careful, they can invalidate their input without expecting it. I advocate for the second option where `decode` consumes `Vec<u8>` by value, zeroizes it and drops. This way it is clear for the caller that they do not own data anymore.

2021-04-07 14:49 UTC, folex commented on identity/src/key_pair.rs
> +            Rsa(kp) => KeyPair::Rsa(rsa::Keypair::from(unsafe { std::mem::transmute::<libp2p_core::identity::rsa::Keypair, rsa::Keypair>(kp) })),
```suggestion
            // safety: these Keypair structures are identitcal
            Rsa(kp) => KeyPair::Rsa(rsa::Keypair::from(unsafe { std::mem::transmute::<libp2p_core::identity::rsa::Keypair, rsa::Keypair>(kp) })),
```

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +            Rsa(pk) => result.extend(pk.encode_pkcs1().to_vec()),
why `to_vec`? It is already Vec<u8>, no reason to clone again

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +    pub fn encode(&self) -> Vec<u8> {
I'd return `Cow<[u8]>` here to avoid copying when possible (for Ed25519 and Secp256k1). Something along these lines:
```suggestion
    pub fn encode(&self) -> Cow<[u8], '_> {
```

2021-04-07 14:49 UTC, folex commented on identity/src/key_pair.rs
> +    pub fn decode(bytes: Vec<u8>, format: String) -> Result<Self, DecodingError> {
Maybe make `format` a enum?
```
pub enum KeyFormat {
  Ed25519,
  Secp256k1
}
// and implement FromStr for it
impl FromStr for KeyFormat { ... }
```

2021-04-07 14:49 UTC, folex commented on identity/src/key_pair.rs
> +    pub fn encode(&self) -> Vec<u8> {
I think you can return `&[u8]` here and let caller decide if they want to produce `Vec` out of it. It's not always needed, and you can avoid extra allocation

2021-04-07 14:49 UTC, folex commented on identity/src/key_pair.rs
> +            "secp256k1" => Ok(Secp256k1(secp256k1::SecretKey::from_bytes(bytes.clone())?.into())),
Why `bytes.clone()`? 
1. No need to clone here - you already own `bytes` because it is passed by value, so you can just `decode(&mut bytes)?`
2. You avoid zeroizing. If you want to keep zeroizing input, you need to change `decode` signature to accept `&mut [u8]`

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +#[repr(u8)]
Is that needed? Why?

@michaelvoronov could you take a look plz?

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +    fn get_prefix(&self) -> u8 {
Maybe create a separate enum for prefix? Like `enum KeyFormat`
```
pub enum KeyFormat {
    Ed25519,
    Secp256k1,
    Rsa
}

impl FromStr for KeyFormat {
   // deserialize from string or return error
}

impl TryFrom<u8> for KeyFormat {
  // deserialize from u8 or return error
}
```

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +        }
Let's return `&[u8]` and avoid `to_vec` calls

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +            Ed25519(key) => PublicKey::Ed25519(ed25519::PublicKey::decode(key.encode().to_vec().as_slice()).unwrap()),
No reason for cloning, let's drop `to_vec`
```suggestion
            Ed25519(key) => PublicKey::Ed25519(ed25519::PublicKey::decode(&key.encode()).unwrap()),
```

2021-04-07 14:49 UTC, folex commented on identity/src/public_key.rs
> +            Secp256k1(key) => PublicKey::Secp256k1(secp256k1::PublicKey::decode(key.encode().to_vec().as_slice()).unwrap()),
ditto
```suggestion
            Secp256k1(key) => PublicKey::Secp256k1(secp256k1::PublicKey::decode(&key.encode()).unwrap()),
```

2021-04-07 14:49 UTC, folex commented on identity/src/rsa.rs
> +use crate::error::*;
Let's avoid wildcard imports everywhere but tests

2021-04-07 14:49 UTC, folex commented on identity/src/error.rs
> +pub struct SigningError {
kudos for creating a separate error type!

2021-04-07 14:49 UTC, folex commented on identity/src/secp256k1.rs
> +    pub fn sign_hash(&self, msg: &[u8]) -> Result<Vec<u8>, SigningError> {
```suggestion
    pub fn sign_hashed(&self, msg: &[u8]) -> Result<Vec<u8>, SigningError> {
```

2021-04-07 14:49 UTC, folex commented on identity/src/secp256k1.rs
> +            .map_err(|_| SigningError::new("failed to parse secp256k1 digest"))?;
Let's set error source here, too

2021-04-07 14:49 UTC, folex commented on identity/src/rsa.rs
> +            Err(e) => Err(SigningError::new("RSA").source(e))
It seems that in that case `e` doesn't hold _any_ information :( So no reason to set it as a source, I fear

2021-04-07 14:49 UTC, folex commented on identity/src/error.rs
> +pub struct SigningError {
I think maybe let's make it a enum? You may take a look at `SQLiteStorageError` and other that implement `thiserror::Error` for example.
```
#[derive(thiserror::Error)]
pub enum SigningError {
   #[error("Failed to sign with RSA")]
   Rsa,
   #[error("Failed to sign with secp256k1: {0})]
   Secp256k1(
       #[from]
       #[source]
       libsecp256k::Error
   ),
   ... // and so on
}
```

This way you don't have to implement Display and Error manually, and all the `source` handling is done idiomatically and automatically

2021-04-07 14:49 UTC, folex commented on identity/src/error.rs
> +pub struct DecodingError {
Same here, let's make it a enum and derive `thiserror::Error`

2021-04-08 08:24 UTC, justprosh commented on identity/src/ed25519.rs
> +        let secret = SecretKey::from_bytes(&mut sk_bytes)
Oh, it's code from libp2p identity, but I'll look deeper into that

2021-04-08 08:27 UTC, justprosh commented on identity/src/secp256k1.rs
> +    pub fn verify_hash(&self, msg: &[u8], sig: &[u8]) -> bool {
This files mostly identical to libp2p identity, I was not sure about changes there but if you think so I will fix

2021-04-08 15:46 UTC, justprosh commented on identity/src/public_key.rs
> +#[repr(u8)]
I don't need it

2021-04-08 15:48 UTC, justprosh commented on identity/src/ed25519.rs
> +        let secret = SecretKey::from_bytes(&mut sk_bytes)
to_bytes return [u8; 32] copy of secret key

2021-04-09 14:03 UTC, folex commented on src/revoke.rs
>      #[error("Signature is incorrect")]
```suggestion
    #[error("Signature is incorrect: {0}")]
```

2021-04-09 15:45 UTC, michaelvoronov reviewed
Additionally, suggest to run `cargo +nightly clippy` and fix all found issues.

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/ed25519.rs
> +        bytes.zeroize();
Why do we need this for PublicKey?

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/ed25519.rs
> +    pub fn decode(mut bytes: Vec<u8>) -> Result<PublicKey, DecodingError> {
`bytes` in this function is used only by ref, so suggest to use `&[u8]` here intead of `Vec<u8>`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/ed25519.rs
> +            .map_err(|e| DecodingError::Ed25519(e))
just `map_err(DecodingError::Ed25519)`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/ed25519.rs
> +    pub fn decode(mut bytes: Vec<u8>) -> Result<PublicKey, DecodingError> {
It's better to use `Self` whether possible: `Result<PublicKey, DecodingError>` => Result<Self, DecodingError>

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/rsa.rs
> +    pub fn decode_pkcs1(pk: Vec<u8>) -> Result<PublicKey, DecodingError> {
Function is named `decode_...`, but it doesn't do decode actually, maybe it's better to name it `from_vec`?

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/signature.rs
> +        let mut result: Vec<u8> = Vec::new();
suggest to use `Vec::with_capacity(1 + sig.0.len())`. It's like reserve in `std::vector`.

2021-04-09 15:45 UTC, michaelvoronov commented on src/trust.rs
> +        let mut vec = Vec::new();
ditto with `Vec::with_capacity`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/public_key.rs
> +        let mut result: Vec<u8> = Vec::new();
ditto with `Vec::with_capacity`

2021-04-09 15:45 UTC, michaelvoronov commented on src/certificate.rs
> +        let mut encoded = Vec::new();
ditto with `Vec::with_capacity`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/public_key.rs
> +            Ed25519(pk) => pk.verify(msg, sig.to_bytes().as_slice()),
Here you create excess `Vec`, because `verify` requires slice. I suggest to change the symantic of `to_bytes` in Signature in such a way to return a slice instead of vec. Moreover, in Rust functions named `to_bytes`/`to_slice` tend to return `&[u8]`/`[u8; N]` and `to_vec` `Vec<u8>`.

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/public_key.rs
> +    pub fn decode(bytes: Vec<u8>) -> Result<PublicKey, DecodingError> {
Suggest to use slice instead of Vec here

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/public_key.rs
> +    pub fn to_bytes(&self) -> Vec<u8> {
Suggest to name it `to_vec`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/signature.rs
> +    pub fn to_bytes(&self) -> Vec<u8> {
ditto with `to_vec`

2021-04-09 15:45 UTC, michaelvoronov commented on identity/src/key_pair.rs
> +    pub fn to_bytes(&self) -> Vec<u8> {
ditto with `to_vec`

2021-04-09 16:00 UTC, michaelvoronov commented on src/trust.rs
> +        vec.extend(issued_for);
The `extend` function has several specialization inside (you could find more details in `spec_extend`). One of it  allows to moving element inside a caller vec instead of copying them. To choose this specialization you need to pass vec by value. And here you pass it by ref.

2021-04-09 16:02 UTC, michaelvoronov commented on src/trust.rs
> +        let pk = PublicKey::decode(arr[offset..offset + pk_len].to_vec())?;
Here you're slicing `arr` without checking its size. It'd cause runtime panic in Rust if it doesn't contain enough bytes.

2021-04-09 16:07 UTC, michaelvoronov commented on identity/src/signature.rs
> +    pub fn encode(&self) -> Vec<u8> {
Suggest to add comment for this and `decode` functions, because it isn't clear what exactly they do from signatures.

2021-04-15 10:45 UTC, michaelvoronov approved these changes

2021-04-15 10:46 UTC, folex approved these changes

2021-04-15 11:00 UTC, merged